(ns net.minecraft.world.storage.loot.functions.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[net.minecraft.world.storage.loot.functions.EnchantRandomly$Serializer])
(require '[net.minecraft.world.storage.loot.functions.EnchantRandomly])
(require '[net.minecraft.world.storage.loot.functions.EnchantWithLevels$Serializer])
(require '[net.minecraft.world.storage.loot.functions.EnchantWithLevels])
(require '[net.minecraft.world.storage.loot.functions.LootFunction$Serializer])
(require '[net.minecraft.world.storage.loot.functions.LootFunction])
(require '[net.minecraft.world.storage.loot.functions.LootFunctionManager$Serializer])
(require '[net.minecraft.world.storage.loot.functions.LootFunctionManager])
(require '[net.minecraft.world.storage.loot.functions.LootingEnchantBonus$Serializer])
(require '[net.minecraft.world.storage.loot.functions.LootingEnchantBonus])
(require '[net.minecraft.world.storage.loot.functions.SetAttributes$Serializer])
(require '[net.minecraft.world.storage.loot.functions.SetAttributes])
(require '[net.minecraft.world.storage.loot.functions.SetCount$Serializer])
(require '[net.minecraft.world.storage.loot.functions.SetCount])
(require '[net.minecraft.world.storage.loot.functions.SetDamage$Serializer])
(require '[net.minecraft.world.storage.loot.functions.SetDamage])
(require '[net.minecraft.world.storage.loot.functions.SetMetadata$Serializer])
(require '[net.minecraft.world.storage.loot.functions.SetMetadata])
(require '[net.minecraft.world.storage.loot.functions.SetNBT$Serializer])
(require '[net.minecraft.world.storage.loot.functions.SetNBT])
(require '[net.minecraft.world.storage.loot.functions.Smelt$Serializer])
(require '[net.minecraft.world.storage.loot.functions.Smelt])
