(ns net.minecraft.nbt.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[net.minecraft.nbt.CompressedStreamTools])
(require '[net.minecraft.nbt.JsonToNBT])
(require '[net.minecraft.nbt.NBTBase])
(require '[net.minecraft.nbt.NBTException])
(require '[net.minecraft.nbt.NBTPrimitive])
(require '[net.minecraft.nbt.NBTSizeTracker])
(require '[net.minecraft.nbt.NBTTagByte])
(require '[net.minecraft.nbt.NBTTagByteArray])
(require '[net.minecraft.nbt.NBTTagCompound])
(require '[net.minecraft.nbt.NBTTagDouble])
(require '[net.minecraft.nbt.NBTTagEnd])
(require '[net.minecraft.nbt.NBTTagFloat])
(require '[net.minecraft.nbt.NBTTagInt])
(require '[net.minecraft.nbt.NBTTagIntArray])
(require '[net.minecraft.nbt.NBTTagList])
(require '[net.minecraft.nbt.NBTTagLong])
(require '[net.minecraft.nbt.NBTTagShort])
(require '[net.minecraft.nbt.NBTTagString])
(require '[net.minecraft.nbt.NBTUtil])
