(ns net.minecraft.entity.boss.dragon.phase.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[net.minecraft.entity.boss.dragon.phase.IPhase])
(require '[net.minecraft.entity.boss.dragon.phase.PhaseBase])
(require '[net.minecraft.entity.boss.dragon.phase.PhaseChargingPlayer])
(require '[net.minecraft.entity.boss.dragon.phase.PhaseDying])
(require '[net.minecraft.entity.boss.dragon.phase.PhaseHoldingPattern])
(require '[net.minecraft.entity.boss.dragon.phase.PhaseHover])
(require '[net.minecraft.entity.boss.dragon.phase.PhaseLanding])
(require '[net.minecraft.entity.boss.dragon.phase.PhaseLandingApproach])
(require '[net.minecraft.entity.boss.dragon.phase.PhaseList])
(require '[net.minecraft.entity.boss.dragon.phase.PhaseManager])
(require '[net.minecraft.entity.boss.dragon.phase.PhaseSittingAttacking])
(require '[net.minecraft.entity.boss.dragon.phase.PhaseSittingBase])
(require '[net.minecraft.entity.boss.dragon.phase.PhaseSittingFlaming])
(require '[net.minecraft.entity.boss.dragon.phase.PhaseSittingScanning])
(require '[net.minecraft.entity.boss.dragon.phase.PhaseStrafePlayer])
(require '[net.minecraft.entity.boss.dragon.phase.PhaseTakeoff])
