(ns net.minecraft.world.storage.loot.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[net.minecraft.world.storage.loot.ILootContainer])
(require '[net.minecraft.world.storage.loot.LootContext$Builder])
(require '[net.minecraft.world.storage.loot.LootContext$EntityTarget$Serializer])
(require '[net.minecraft.world.storage.loot.LootContext$EntityTarget])
(require '[net.minecraft.world.storage.loot.LootContext])
(require '[net.minecraft.world.storage.loot.LootEntry$Serializer])
(require '[net.minecraft.world.storage.loot.LootEntry])
(require '[net.minecraft.world.storage.loot.LootEntryEmpty])
(require '[net.minecraft.world.storage.loot.LootEntryItem])
(require '[net.minecraft.world.storage.loot.LootEntryTable])
(require '[net.minecraft.world.storage.loot.LootPool$Serializer])
(require '[net.minecraft.world.storage.loot.LootPool])
(require '[net.minecraft.world.storage.loot.LootTable$Serializer])
(require '[net.minecraft.world.storage.loot.LootTable])
(require '[net.minecraft.world.storage.loot.LootTableList])
(require '[net.minecraft.world.storage.loot.LootTableManager])
(require '[net.minecraft.world.storage.loot.RandomValueRange$Serializer])
(require '[net.minecraft.world.storage.loot.RandomValueRange])
