(ns net.minecraft.entity.projectile.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[net.minecraft.entity.projectile.EntityArrow$PickupStatus])
(require '[net.minecraft.entity.projectile.EntityArrow])
(require '[net.minecraft.entity.projectile.EntityDragonFireball])
(require '[net.minecraft.entity.projectile.EntityEgg])
(require '[net.minecraft.entity.projectile.EntityEvokerFangs])
(require '[net.minecraft.entity.projectile.EntityFireball])
(require '[net.minecraft.entity.projectile.EntityFishHook])
(require '[net.minecraft.entity.projectile.EntityLargeFireball])
(require '[net.minecraft.entity.projectile.EntityLlamaSpit])
(require '[net.minecraft.entity.projectile.EntityPotion])
(require '[net.minecraft.entity.projectile.EntityShulkerBullet])
(require '[net.minecraft.entity.projectile.EntitySmallFireball])
(require '[net.minecraft.entity.projectile.EntitySnowball])
(require '[net.minecraft.entity.projectile.EntitySpectralArrow])
(require '[net.minecraft.entity.projectile.EntityThrowable])
(require '[net.minecraft.entity.projectile.EntityTippedArrow])
(require '[net.minecraft.entity.projectile.EntityWitherSkull])
(require '[net.minecraft.entity.projectile.ProjectileHelper])
