(ns net.minecraft.world.storage.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[net.minecraft.world.storage.DerivedWorldInfo])
(require '[net.minecraft.world.storage.IPlayerFileData])
(require '[net.minecraft.world.storage.ISaveFormat])
(require '[net.minecraft.world.storage.ISaveHandler])
(require '[net.minecraft.world.storage.IThreadedFileIO])
(require '[net.minecraft.world.storage.MapData])
(require '[net.minecraft.world.storage.MapDecoration$Type])
(require '[net.minecraft.world.storage.MapDecoration])
(require '[net.minecraft.world.storage.MapStorage])
(require '[net.minecraft.world.storage.SaveDataMemoryStorage])
(require '[net.minecraft.world.storage.SaveFormatOld])
(require '[net.minecraft.world.storage.SaveHandler])
(require '[net.minecraft.world.storage.SaveHandlerMP])
(require '[net.minecraft.world.storage.ThreadedFileIOBase])
(require '[net.minecraft.world.storage.WorldInfo])
(require '[net.minecraft.world.storage.WorldSummary])
