(ns net.minecraftforge.common.util.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[net.minecraftforge.common.util.BlockSnapshot])
(require '[net.minecraftforge.common.util.ChunkCoordComparator])
(require '[net.minecraftforge.common.util.CompoundDataFixer])
(require '[net.minecraftforge.common.util.Constants$NBT])
(require '[net.minecraftforge.common.util.Constants])
(require '[net.minecraftforge.common.util.EnumHelper])
(require '[net.minecraftforge.common.util.FakePlayer])
(require '[net.minecraftforge.common.util.FakePlayerFactory])
(require '[net.minecraftforge.common.util.IDataFixerData])
(require '[net.minecraftforge.common.util.INBTSerializable])
(require '[net.minecraftforge.common.util.Java6Utils])
(require '[net.minecraftforge.common.util.JsonUtils$ImmutableListTypeAdapter])
(require '[net.minecraftforge.common.util.JsonUtils$ImmutableMapTypeAdapter])
(require '[net.minecraftforge.common.util.JsonUtils])
(require '[net.minecraftforge.common.util.ModFixs])
(require '[net.minecraftforge.common.util.WorldCapabilityData])
