(ns net.minecraft.client.gui.inventory.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[net.minecraft.client.gui.inventory.CreativeCrafting])
(require '[net.minecraft.client.gui.inventory.GuiBeacon])
(require '[net.minecraft.client.gui.inventory.GuiBrewingStand])
(require '[net.minecraft.client.gui.inventory.GuiChest])
(require '[net.minecraft.client.gui.inventory.GuiContainer])
(require '[net.minecraft.client.gui.inventory.GuiContainerCreative])
(require '[net.minecraft.client.gui.inventory.GuiCrafting])
(require '[net.minecraft.client.gui.inventory.GuiDispenser])
(require '[net.minecraft.client.gui.inventory.GuiEditCommandBlockMinecart])
(require '[net.minecraft.client.gui.inventory.GuiEditSign])
(require '[net.minecraft.client.gui.inventory.GuiEditStructure])
(require '[net.minecraft.client.gui.inventory.GuiFurnace])
(require '[net.minecraft.client.gui.inventory.GuiInventory])
(require '[net.minecraft.client.gui.inventory.GuiScreenHorseInventory])
(require '[net.minecraft.client.gui.inventory.GuiShulkerBox])
