(ns net.minecraft.util.text.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[net.minecraft.util.text.ITextComponent$Serializer])
(require '[net.minecraft.util.text.ITextComponent])
(require '[net.minecraft.util.text.Style$Serializer])
(require '[net.minecraft.util.text.Style])
(require '[net.minecraft.util.text.TextComponentBase])
(require '[net.minecraft.util.text.TextComponentScore])
(require '[net.minecraft.util.text.TextComponentSelector])
(require '[net.minecraft.util.text.TextComponentString])
(require '[net.minecraft.util.text.TextComponentTranslation])
(require '[net.minecraft.util.text.TextComponentTranslationFormatException])
(require '[net.minecraft.util.text.TextComponentUtils])
(require '[net.minecraft.util.text.TextFormatting])
