(ns net.minecraft.client.renderer.texture.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[net.minecraft.client.renderer.texture.AbstractTexture])
(require '[net.minecraft.client.renderer.texture.DynamicTexture])
(require '[net.minecraft.client.renderer.texture.ITextureMapPopulator])
(require '[net.minecraft.client.renderer.texture.ITextureObject])
(require '[net.minecraft.client.renderer.texture.ITickable])
(require '[net.minecraft.client.renderer.texture.ITickableTextureObject])
(require '[net.minecraft.client.renderer.texture.LayeredColorMaskTexture])
(require '[net.minecraft.client.renderer.texture.LayeredTexture])
(require '[net.minecraft.client.renderer.texture.PngSizeInfo])
(require '[net.minecraft.client.renderer.texture.SimpleTexture])
(require '[net.minecraft.client.renderer.texture.Stitcher$Holder])
(require '[net.minecraft.client.renderer.texture.Stitcher$Slot])
(require '[net.minecraft.client.renderer.texture.Stitcher])
(require '[net.minecraft.client.renderer.texture.TextureAtlasSprite])
(require '[net.minecraft.client.renderer.texture.TextureManager])
(require '[net.minecraft.client.renderer.texture.TextureMap])
(require '[net.minecraft.client.renderer.texture.TextureUtil])
