(ns net.minecraftforge.common.model.animation.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[net.minecraftforge.common.model.animation.AnimationStateMachine])
(require '[net.minecraftforge.common.model.animation.CapabilityAnimation$DefaultItemAnimationCapabilityProvider])
(require '[net.minecraftforge.common.model.animation.CapabilityAnimation])
(require '[net.minecraftforge.common.model.animation.Clips$ClipReference])
(require '[net.minecraftforge.common.model.animation.Clips$CommonClipTypeAdapterFactory])
(require '[net.minecraftforge.common.model.animation.Clips$IdentityClip])
(require '[net.minecraftforge.common.model.animation.Clips$ModelClip])
(require '[net.minecraftforge.common.model.animation.Clips$SlerpClip])
(require '[net.minecraftforge.common.model.animation.Clips$TimeClip])
(require '[net.minecraftforge.common.model.animation.Clips$TriggerClip])
(require '[net.minecraftforge.common.model.animation.Clips])
(require '[net.minecraftforge.common.model.animation.IAnimationStateMachine])
(require '[net.minecraftforge.common.model.animation.IClip])
(require '[net.minecraftforge.common.model.animation.IJoint])
(require '[net.minecraftforge.common.model.animation.IJointClip])
(require '[net.minecraftforge.common.model.animation.JointClips$IdentityJointClip])
(require '[net.minecraftforge.common.model.animation.JointClips$NodeJointClip])
(require '[net.minecraftforge.common.model.animation.JointClips])
