(ns net.minecraft.client.audio.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[net.minecraft.client.audio.ElytraSound])
(require '[net.minecraft.client.audio.GuardianSound])
(require '[net.minecraft.client.audio.ISound$AttenuationType])
(require '[net.minecraft.client.audio.ISound])
(require '[net.minecraft.client.audio.ISoundEventAccessor])
(require '[net.minecraft.client.audio.ISoundEventListener])
(require '[net.minecraft.client.audio.ITickableSound])
(require '[net.minecraft.client.audio.MovingSound])
(require '[net.minecraft.client.audio.MovingSoundMinecart])
(require '[net.minecraft.client.audio.MovingSoundMinecartRiding])
(require '[net.minecraft.client.audio.MusicTicker$MusicType])
(require '[net.minecraft.client.audio.MusicTicker])
(require '[net.minecraft.client.audio.PositionedSound])
(require '[net.minecraft.client.audio.PositionedSoundRecord])
(require '[net.minecraft.client.audio.Sound$Type])
(require '[net.minecraft.client.audio.Sound])
(require '[net.minecraft.client.audio.SoundEventAccessor])
(require '[net.minecraft.client.audio.SoundHandler])
(require '[net.minecraft.client.audio.SoundList])
(require '[net.minecraft.client.audio.SoundListSerializer])
(require '[net.minecraft.client.audio.SoundManager])
(require '[net.minecraft.client.audio.SoundRegistry])
