(ns net.minecraftforge.fluids.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[net.minecraftforge.fluids.BlockFluidBase])
(require '[net.minecraftforge.fluids.BlockFluidClassic])
(require '[net.minecraftforge.fluids.BlockFluidFinite])
(require '[net.minecraftforge.fluids.DispenseFluidContainer])
(require '[net.minecraftforge.fluids.Fluid])
(require '[net.minecraftforge.fluids.FluidActionResult])
(require '[net.minecraftforge.fluids.FluidEvent$FluidDrainingEvent])
(require '[net.minecraftforge.fluids.FluidEvent$FluidFillingEvent])
(require '[net.minecraftforge.fluids.FluidEvent$FluidMotionEvent])
(require '[net.minecraftforge.fluids.FluidEvent$FluidSpilledEvent])
(require '[net.minecraftforge.fluids.FluidEvent])
(require '[net.minecraftforge.fluids.FluidRegistry$FluidRegisterEvent])
(require '[net.minecraftforge.fluids.FluidRegistry])
(require '[net.minecraftforge.fluids.FluidStack])
(require '[net.minecraftforge.fluids.FluidTank])
(require '[net.minecraftforge.fluids.FluidTankInfo])
(require '[net.minecraftforge.fluids.FluidUtil])
(require '[net.minecraftforge.fluids.IFluidBlock])
(require '[net.minecraftforge.fluids.IFluidTank])
(require '[net.minecraftforge.fluids.UniversalBucket])
