(ns net.minecraftforge.client.model.animation.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[net.minecraftforge.client.model.animation.Animation])
(require '[net.minecraftforge.client.model.animation.AnimationItemOverrideList])
(require '[net.minecraftforge.client.model.animation.AnimationModelBase])
(require '[net.minecraftforge.client.model.animation.AnimationTESR])
(require '[net.minecraftforge.client.model.animation.FastTESR])
(require '[net.minecraftforge.client.model.animation.IAnimatedModel])
(require '[net.minecraftforge.client.model.animation.ModelBlockAnimation$MBClip$MBJointClip])
(require '[net.minecraftforge.client.model.animation.ModelBlockAnimation$MBClip])
(require '[net.minecraftforge.client.model.animation.ModelBlockAnimation$MBJoint])
(require '[net.minecraftforge.client.model.animation.ModelBlockAnimation$MBJointWeight])
(require '[net.minecraftforge.client.model.animation.ModelBlockAnimation$MBVariableClip])
(require '[net.minecraftforge.client.model.animation.ModelBlockAnimation$Parameter$Interpolation])
(require '[net.minecraftforge.client.model.animation.ModelBlockAnimation$Parameter$Type])
(require '[net.minecraftforge.client.model.animation.ModelBlockAnimation$Parameter$Variable])
(require '[net.minecraftforge.client.model.animation.ModelBlockAnimation$Parameter])
(require '[net.minecraftforge.client.model.animation.ModelBlockAnimation])
