(ns net.minecraftforge.fml.common.gameevent.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[net.minecraftforge.fml.common.gameevent.InputEvent$KeyInputEvent])
(require '[net.minecraftforge.fml.common.gameevent.InputEvent$MouseInputEvent])
(require '[net.minecraftforge.fml.common.gameevent.InputEvent])
(require '[net.minecraftforge.fml.common.gameevent.PlayerEvent$ItemCraftedEvent])
(require '[net.minecraftforge.fml.common.gameevent.PlayerEvent$ItemPickupEvent])
(require '[net.minecraftforge.fml.common.gameevent.PlayerEvent$ItemSmeltedEvent])
(require '[net.minecraftforge.fml.common.gameevent.PlayerEvent$PlayerChangedDimensionEvent])
(require '[net.minecraftforge.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent])
(require '[net.minecraftforge.fml.common.gameevent.PlayerEvent$PlayerLoggedOutEvent])
(require '[net.minecraftforge.fml.common.gameevent.PlayerEvent$PlayerRespawnEvent])
(require '[net.minecraftforge.fml.common.gameevent.PlayerEvent])
(require '[net.minecraftforge.fml.common.gameevent.TickEvent$ClientTickEvent])
(require '[net.minecraftforge.fml.common.gameevent.TickEvent$Phase])
(require '[net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent])
(require '[net.minecraftforge.fml.common.gameevent.TickEvent$RenderTickEvent])
(require '[net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent])
(require '[net.minecraftforge.fml.common.gameevent.TickEvent$Type])
(require '[net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent])
(require '[net.minecraftforge.fml.common.gameevent.TickEvent])
