(ns net.minecraft.scoreboard.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[net.minecraft.scoreboard.IScoreCriteria$EnumRenderType])
(require '[net.minecraft.scoreboard.IScoreCriteria])
(require '[net.minecraft.scoreboard.Score])
(require '[net.minecraft.scoreboard.ScoreCriteria])
(require '[net.minecraft.scoreboard.ScoreCriteriaColored])
(require '[net.minecraft.scoreboard.ScoreCriteriaHealth])
(require '[net.minecraft.scoreboard.ScoreCriteriaReadOnly])
(require '[net.minecraft.scoreboard.ScoreCriteriaStat])
(require '[net.minecraft.scoreboard.ScoreObjective])
(require '[net.minecraft.scoreboard.ScorePlayerTeam])
(require '[net.minecraft.scoreboard.Scoreboard])
(require '[net.minecraft.scoreboard.ScoreboardSaveData])
(require '[net.minecraft.scoreboard.ServerScoreboard])
(require '[net.minecraft.scoreboard.Team$CollisionRule])
(require '[net.minecraft.scoreboard.Team$EnumVisible])
(require '[net.minecraft.scoreboard.Team])
