(ns net.minecraft.client.renderer.tileentity.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[net.minecraft.client.renderer.tileentity.RenderEnderCrystal])
(require '[net.minecraft.client.renderer.tileentity.RenderItemFrame])
(require '[net.minecraft.client.renderer.tileentity.RenderWitherSkull])
(require '[net.minecraft.client.renderer.tileentity.TileEntityBannerRenderer])
(require '[net.minecraft.client.renderer.tileentity.TileEntityBeaconRenderer])
(require '[net.minecraft.client.renderer.tileentity.TileEntityChestRenderer])
(require '[net.minecraft.client.renderer.tileentity.TileEntityEnchantmentTableRenderer])
(require '[net.minecraft.client.renderer.tileentity.TileEntityEndGatewayRenderer])
(require '[net.minecraft.client.renderer.tileentity.TileEntityEndPortalRenderer])
(require '[net.minecraft.client.renderer.tileentity.TileEntityEnderChestRenderer])
(require '[net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer])
(require '[net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer])
(require '[net.minecraft.client.renderer.tileentity.TileEntityPistonRenderer])
(require '[net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher])
(require '[net.minecraft.client.renderer.tileentity.TileEntityShulkerBoxRenderer])
(require '[net.minecraft.client.renderer.tileentity.TileEntitySignRenderer])
(require '[net.minecraft.client.renderer.tileentity.TileEntitySkullRenderer])
(require '[net.minecraft.client.renderer.tileentity.TileEntitySpecialRenderer])
(require '[net.minecraft.client.renderer.tileentity.TileEntityStructureRenderer])
